import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { NarrialButton } from '@/components/narrial-button';
import { ContentPerformanceCard, PublishedPostCard, PublishingTabs, PublishingThumbnail } from '@/features/publishing/publishing-components';
import { filterPublishedPosts, PUBLISHED_POSTS, PUBLISHING_WEEK, type PlatformFilter, type ScheduledPost, type TimeRange } from '@/features/publishing/publishing-data';
import { PublishingIcon } from '@/features/publishing/publishing-icons';

const LIME = '#A8FF00';
const ranges: { value: TimeRange; label: string }[] = [{ value: '7-days', label: 'Last 7 days' }, { value: '30-days', label: 'Last 30 days' }, { value: 'all-time', label: 'All time' }];
const platforms: { value: PlatformFilter; label: string }[] = [{ value: 'all', label: 'All platforms' }, { value: 'instagram', label: 'Instagram' }, { value: 'tiktok', label: 'TikTok' }, { value: 'youtube', label: 'YouTube' }, { value: 'facebook', label: 'Facebook' }];

function FilterSelect<T extends string>({ label, options, value, onChange }: { label: string; options: { value: T; label: string }[]; value: T; onChange: (value: T) => void }) {
  const [open, setOpen] = useState(false);
  const activeLabel = options.find((option) => option.value === value)?.label ?? label;
  return <><Pressable accessibilityRole="button" accessibilityLabel={`${label}: ${activeLabel}`} accessibilityState={{ expanded: open }} onPress={() => setOpen(true)} style={[styles.select, value !== options[0].value && styles.selectActive]}><Text numberOfLines={1} style={[styles.selectText, value !== options[0].value && styles.selectTextActive]}>{activeLabel}</Text><PublishingIcon name="chevron" size={19} color={value !== options[0].value ? LIME : '#FFF'}/></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><Pressable accessibilityRole="button" accessibilityLabel={`Close ${label}`} onPress={() => setOpen(false)} style={styles.backdrop}><View style={styles.optionMenu}>{options.map((option) => <Pressable key={option.value} accessibilityRole="menuitem" accessibilityState={{ selected: option.value === value }} onPress={() => { onChange(option.value); setOpen(false); }} style={[styles.option, option.value === value && styles.optionActive]}><Text style={[styles.optionText, option.value === value && styles.optionTextActive]}>{option.label}</Text>{option.value === value && <PublishingIcon name="check" color={LIME}/>}</Pressable>)}</View></Pressable></Modal></>;
}

function ScheduleSummary({ icon, value, label, warning = false, compact }: { icon: 'calendar' | 'warning' | 'layers'; value: string; label: string; warning?: boolean; compact: boolean }) {
  const color = warning ? '#FFC72C' : '#D8D8D8';
  return <View accessible accessibilityLabel={`${value} ${label}`} style={[styles.scheduleSummary, compact && styles.scheduleSummaryCompact]}><View style={[styles.scheduleSummaryIcon, compact && styles.scheduleSummaryIconCompact]}><PublishingIcon name={icon} color={color} size={compact ? 21 : 25}/></View><View style={compact && styles.scheduleSummaryCopyCompact}><Text style={[styles.scheduleSummaryValue, compact && styles.scheduleSummaryValueCompact]}>{value}</Text><Text numberOfLines={2} style={[styles.scheduleSummaryLabel, compact && styles.scheduleSummaryLabelCompact]}>{label}</Text></View></View>;
}

function ScheduleCard({ post, compact, onMenu }: { post: ScheduledPost; compact: boolean; onMenu: () => void }) {
  const needsApproval = post.status === 'needs-approval';
  return <View style={[styles.timelineRow, compact && styles.timelineRowCompact]}><View style={styles.timelineMarker}/><View style={[styles.scheduledCard, compact && styles.scheduledCardCompact]}>
    <PublishingThumbnail thumbnail={post.thumbnail} duration={post.duration} platforms={post.platforms} compact={compact}/><View style={styles.scheduledCopy}>
      <View style={styles.scheduledTopRow}><View style={styles.timeRow}><PublishingIcon name="clock" color="#CFCFCF" size={21}/><Text style={styles.timeText}>{post.time}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`More options for ${post.title}`} onPress={onMenu} hitSlop={10} style={styles.moreButton}><PublishingIcon name="more"/></Pressable></View>
      <Text style={styles.scheduledTitle}>{post.title}</Text>
      <View accessible accessibilityLabel={needsApproval ? 'Needs approval' : 'Ready'} style={[styles.scheduleStatus, needsApproval && styles.scheduleStatusWarning]}><PublishingIcon name={needsApproval ? 'warning' : 'check'} color={needsApproval ? '#FFC72C' : '#090909'} size={19}/><Text style={[styles.scheduleStatusText, needsApproval && styles.scheduleStatusTextWarning]}>{needsApproval ? 'Needs approval' : 'Ready'}</Text></View>
    </View>
  </View></View>;
}

function ScheduledContent({ compact }: { compact: boolean }) {
  const [selectedDayId, setSelectedDayId] = useState(PUBLISHING_WEEK.find((day) => day.isToday)?.id ?? PUBLISHING_WEEK[0].id);
  const selectedDay = PUBLISHING_WEEK.find((day) => day.id === selectedDayId) ?? PUBLISHING_WEEK[0];
  const posts = selectedDay.posts;
  const scheduledCount = PUBLISHING_WEEK.reduce((total, day) => total + day.posts.length, 0);
  const approvalCount = PUBLISHING_WEEK.flatMap((day) => day.posts).filter((post) => post.status === 'needs-approval').length;
  const openGenerator = () => router.push('/generator');
  const dayLabel = selectedDay.isToday ? 'Today' : `${selectedDay.weekday[0]}${selectedDay.weekday.slice(1).toLowerCase()}`;

  return <>
    <View style={styles.weekSection}><Text style={styles.weekRange}>AUG 18–24</Text><View accessibilityRole="tablist" accessibilityLabel="Publishing week" style={styles.weekRow}>{PUBLISHING_WEEK.map((day, index) => <View key={day.id} style={styles.dayCellWrap}><Pressable accessibilityRole="tab" accessibilityLabel={`${day.weekday}, August ${day.date}${day.hasPosts ? ', posts scheduled' : ''}`} accessibilityState={{ selected: selectedDayId === day.id }} onPress={() => setSelectedDayId(day.id)} style={({ pressed }) => [styles.dayCell, selectedDayId === day.id && styles.dayCellSelected, pressed && styles.pressed]}><Text style={[styles.weekday, selectedDayId === day.id && styles.dayTextSelected]}>{day.weekday}</Text><Text style={[styles.dayNumber, selectedDayId === day.id && styles.dayTextSelected]}>{day.date}</Text></Pressable><View style={[styles.dayDot, day.hasPosts && styles.dayDotActive, selectedDayId === day.id && styles.dayDotSelected]}/>{index < PUBLISHING_WEEK.length - 1 && <View style={styles.dayDivider}/>}</View>)}</View></View>
    <View style={[styles.scheduleSummaries, compact && styles.scheduleSummariesCompact]}><ScheduleSummary compact={compact} icon="calendar" value={String(scheduledCount)} label="Scheduled"/><ScheduleSummary compact={compact} icon="warning" value={String(approvalCount)} label="Need approval" warning/><ScheduleSummary compact={compact} icon="layers" value="3" label="Platforms"/></View>
    <View style={[styles.todayHeader, compact && styles.todayHeaderCompact]}><View><Text accessibilityRole="header" style={styles.todayTitle}>{dayLabel}</Text><Text style={styles.todayDate}>{selectedDay.weekday === 'WED' ? 'Wednesday' : dayLabel}, {selectedDay.date} August</Text></View><View accessible accessibilityLabel="AI recommendation: Best audience window 8:45 to 9:30 AM" style={[styles.recommendation, compact && styles.recommendationCompact]}><PublishingIcon name="sparkle" color="#D8D8D8"/><Text style={styles.recommendationText}>Best audience window: 8:45–9:30 AM</Text></View></View>
    {posts.length ? <View style={styles.timeline}>{posts.map((post) => <ScheduleCard key={post.id} post={post} compact={compact} onMenu={() => Alert.alert(post.title, 'Choose an action', [{ text: 'Reschedule', onPress: () => Alert.alert('Reschedule', 'Date and time controls are ready for the publishing API.') }, { text: 'Duplicate', onPress: () => Alert.alert('Duplicated', 'A mock copy was added to the scheduling workflow.') }, { text: 'Cancel', style: 'cancel' }])}/>)}</View> : <View accessibilityRole="summary" style={styles.emptyState}><PublishingIcon name="calendar" color={LIME} size={32}/><Text style={styles.emptyTitle}>Nothing scheduled</Text><Text style={styles.emptyCopy}>This day is open. Add a video to keep your publishing rhythm going.</Text></View>}
    <Pressable accessibilityRole="button" accessibilityLabel="Schedule another video" onPress={openGenerator} style={({ pressed }) => [styles.emptySlot, pressed && styles.pressed]}><View style={styles.plusCircle}><PublishingIcon name="plus" color="#D8D8D8"/></View><Text style={styles.emptySlotText}>Schedule another video</Text></Pressable>
    <Pressable accessibilityRole="button" accessibilityLabel="Create and schedule" onPress={openGenerator} style={({ pressed }) => [styles.createButton, pressed && styles.pressed]}><PublishingIcon name="calendar" color="#080808" size={28}/><Text style={styles.createButtonText}>Create & schedule</Text></Pressable>
  </>;
}

export default function PublishingPage() {
  const { width } = useWindowDimensions();
  const compact = width < 390;
  const [tab, setTab] = useState<'scheduled' | 'published'>('scheduled');
  const [range, setRange] = useState<TimeRange>('7-days');
  const [platform, setPlatform] = useState<PlatformFilter>('all');
  const [selected, setSelected] = useState<string[]>([]);
  const [state, setState] = useState<'ready' | 'loading' | 'error'>('ready');
  const posts = useMemo(() => filterPublishedPosts(PUBLISHED_POSTS, range, platform), [range, platform]);
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 2 ? [...current, id] : [current[1], id]);

  const compare = () => selected.length < 2 ? Alert.alert('Select two posts', 'Tap any two post cards, then choose Compare posts.') : Alert.alert('Post comparison', `${selected.map((id) => PUBLISHED_POSTS.find((post) => post.id === id)?.title).join(' vs. ')} selected for comparison.`);
  const startAutoLearning = () => Alert.alert('Start auto-learning?', 'Narrial will learn from your strongest posts and use those insights to improve the next content you create and publish.', [{ text: 'Not now', style: 'cancel' }, { text: 'Start', onPress: () => router.push('/generator') }]);
  return <SafeAreaView style={styles.screen} edges={['top', 'bottom']}><View style={styles.page}>
    <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.canGoBack() ? router.back() : router.replace('/generator')} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]}><PublishingIcon name="back" size={27}/></Pressable><Text accessibilityRole="header" style={[styles.title, compact && styles.titleCompact]}>Publishing</Text><Pressable accessibilityRole="button" accessibilityLabel="Publishing settings" onPress={() => Alert.alert('Publishing settings', 'Publishing preferences and account defaults are ready for API connection.')} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]}><PublishingIcon name="calendar" size={25}/></Pressable></View>
    <PublishingTabs active={tab} onChange={setTab}/>
    <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
      {tab === 'scheduled' ? <ScheduledContent compact={compact}/> : <>
        <View style={styles.filters}><FilterSelect label="Time range" options={ranges} value={range} onChange={setRange}/><FilterSelect label="Platform" options={platforms} value={platform} onChange={setPlatform}/><Pressable accessibilityRole="button" accessibilityLabel="More filters" onPress={() => Alert.alert('More filters', 'Status, performance, and destination filters can be connected here.')} style={styles.filterButton}><PublishingIcon name="filter"/></Pressable></View>
        <View style={styles.section}><Text accessibilityRole="header" style={styles.sectionTitle}>Content performance</Text><Text style={styles.dateRange}>{range === '7-days' ? '19–25 August' : range === '30-days' ? 'Last 30 days' : 'All publishing history'}</Text><ContentPerformanceCard posts={posts.length} views="248K" engagement="8.4%"/></View>
        <View style={styles.section}><View style={styles.sectionHeader}><Text accessibilityRole="header" style={styles.sectionTitle}>Recent posts</Text><Pressable accessibilityRole="link" onPress={() => Alert.alert('Analytics', 'Opening the full publishing analytics workspace.')}><Text style={styles.analyticsLink}>View analytics</Text></Pressable></View>
          {state === 'loading' ? <View accessibilityLabel="Loading published posts" accessibilityState={{ busy: true }} style={styles.stateCard}><ActivityIndicator color={LIME}/><Text style={styles.stateCopy}>Loading published posts…</Text></View> : state === 'error' ? <View style={styles.stateCard}><Text style={styles.stateTitle}>Posts unavailable</Text><Text style={styles.stateCopy}>We couldn’t load publishing history.</Text><Pressable accessibilityRole="button" onPress={() => setState('ready')} style={styles.retry}><Text style={styles.retryText}>Try again</Text></Pressable></View> : posts.length === 0 ? <View style={styles.stateCard}><Text style={styles.stateTitle}>No published posts</Text><Text style={styles.stateCopy}>No posts match these filters. Try another platform or time range.</Text><Pressable accessibilityRole="button" onPress={() => { setPlatform('all'); setRange('all-time'); }} style={styles.retry}><Text style={styles.retryText}>Clear filters</Text></Pressable></View> : <View style={styles.list}>{posts.map((post) => <PublishedPostCard key={post.id} post={post} selected={selected.includes(post.id)} onToggle={() => toggle(post.id)} onMenu={() => Alert.alert(post.title, 'View details, retry failed destinations, duplicate, or remove this post from history.')} />)}</View>}
        </View>
        <View accessible accessibilityLabel="AI insight: Motivation hooks are driving 22 percent more watch time" style={styles.insight}><PublishingIcon name="sparkle" size={25} color={LIME}/><Text style={styles.insightText}>Motivation hooks are driving 22% more watch time</Text></View>
        <View style={styles.autoLearnIntro}><Text style={styles.autoLearnTitle}>Make every new post smarter</Text><Text style={styles.autoLearnCopy}>Narrial learns what worked, then applies those insights to improve your next content.</Text></View>
        <View style={styles.actions}><NarrialButton label={`Compare posts${selected.length ? ` (${selected.length}/2)` : ''}`} variant="secondary" onPress={compare}/><NarrialButton label="Start auto-learn & publish" onPress={startAutoLearning}/></View>
        <Pressable accessibilityRole="button" accessibilityLabel="Toggle loading preview" onLongPress={() => setState(state === 'loading' ? 'ready' : 'loading')} onPress={() => {}} style={styles.hiddenStateTrigger}/>
      </>}
    </ScrollView>
  </View></SafeAreaView>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#020202' }, page: { flex: 1, width: '100%', maxWidth: 820, alignSelf: 'center' }, header: { minHeight: 74, flexDirection: 'row', alignItems: 'center', gap: 18, paddingHorizontal: 20 }, circleButton: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#404040', backgroundColor: '#050505' }, title: { flex: 1, color: '#FFF', fontSize: 35, fontWeight: '900', letterSpacing: -1 }, titleCompact: { fontSize: 29 }, pressed: { opacity: 0.72, transform: [{ scale: 0.97 }] }, scrollContent: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 26 },
  weekSection: { marginBottom: 20 }, weekRange: { color: '#A7A7A7', fontSize: 15, fontWeight: '700' }, weekRow: { height: 105, flexDirection: 'row', marginTop: 8 }, dayCellWrap: { flex: 1, alignItems: 'center', justifyContent: 'flex-start' }, dayCell: { width: '90%', minHeight: 68, alignItems: 'center', justifyContent: 'center', borderRadius: 34 }, dayCellSelected: { backgroundColor: LIME }, weekday: { color: '#AAA', fontSize: 12, fontWeight: '700' }, dayNumber: { marginTop: 2, color: '#F4F4F4', fontSize: 25, fontWeight: '700' }, dayTextSelected: { color: '#060606' }, dayDot: { width: 9, height: 9, marginTop: 7, borderRadius: 5, backgroundColor: '#555' }, dayDotActive: { backgroundColor: '#A7A7A7' }, dayDotSelected: { backgroundColor: LIME }, dayDivider: { position: 'absolute', right: 0, top: 17, width: 1, height: 54, backgroundColor: '#333' },
  scheduleSummaries: { flexDirection: 'row', gap: 10, marginBottom: 28 }, scheduleSummariesCompact: { gap: 7 }, scheduleSummary: { flex: 1, minHeight: 103, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 13, borderRadius: 17, borderWidth: 1, borderColor: '#303030', backgroundColor: '#090909' }, scheduleSummaryCompact: { minHeight: 116, flexDirection: 'column', justifyContent: 'center', gap: 6, paddingHorizontal: 5, paddingVertical: 10 }, scheduleSummaryIcon: { width: 43, height: 43, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: '#1B1B1B' }, scheduleSummaryIconCompact: { width: 36, height: 36, borderRadius: 18 }, scheduleSummaryCopyCompact: { alignItems: 'center' }, scheduleSummaryValue: { color: '#FFF', fontSize: 25, fontWeight: '900' }, scheduleSummaryValueCompact: { fontSize: 21 }, scheduleSummaryLabel: { color: '#BBB', fontSize: 12 }, scheduleSummaryLabelCompact: { minHeight: 28, fontSize: 11, lineHeight: 14, textAlign: 'center' },
  todayHeader: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12, marginBottom: 16 }, todayHeaderCompact: { alignItems: 'stretch', flexDirection: 'column' }, todayTitle: { color: '#FFF', fontSize: 27, fontWeight: '900' }, todayDate: { marginTop: 3, color: '#B8B8B8', fontSize: 15 }, recommendation: { maxWidth: '58%', minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 13, borderRadius: 12, borderWidth: 1, borderColor: '#343434', backgroundColor: '#090909' }, recommendationCompact: { maxWidth: '100%' }, recommendationText: { flexShrink: 1, color: '#D5D5D5', fontSize: 13, lineHeight: 18 },
  timeline: { gap: 15, marginBottom: 15, borderLeftWidth: 1, borderLeftColor: '#3A3A3A', paddingLeft: 23 }, timelineRow: { position: 'relative' }, timelineRowCompact: {}, timelineMarker: { position: 'absolute', left: -29, top: 20, zIndex: 2, width: 11, height: 11, borderRadius: 6, borderWidth: 2, borderColor: '#090909', backgroundColor: '#BDBDBD' }, scheduledCard: { minHeight: 225, flexDirection: 'row', gap: 14, padding: 13, borderRadius: 17, borderWidth: 1, borderColor: '#303030', backgroundColor: '#090A09' }, scheduledCardCompact: { minHeight: 196, flexDirection: 'row', gap: 11, padding: 10 }, scheduledCopy: { flex: 1, minWidth: 0 }, scheduledTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, timeRow: { flexDirection: 'row', alignItems: 'center', gap: 6 }, timeText: { color: '#F0F0F0', fontSize: 17, fontWeight: '700' }, moreButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, scheduledTitle: { marginTop: 10, color: '#FFF', fontSize: 20, lineHeight: 24, fontWeight: '900' }, scheduleStatus: { alignSelf: 'flex-start', minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 12, paddingHorizontal: 13, borderRadius: 20, backgroundColor: LIME }, scheduleStatusWarning: { borderWidth: 1, borderColor: '#FFC72C', backgroundColor: 'transparent' }, scheduleStatusText: { color: '#080808', fontSize: 14, fontWeight: '800' }, scheduleStatusTextWarning: { color: '#FFC72C' },
  emptyState: { alignItems: 'center', marginBottom: 16, padding: 28, borderRadius: 17, borderWidth: 1, borderColor: '#303030', backgroundColor: '#080808' }, emptyTitle: { marginTop: 10, color: '#FFF', fontSize: 19, fontWeight: '800' }, emptyCopy: { maxWidth: 390, marginTop: 6, color: '#AAA', textAlign: 'center', lineHeight: 20 }, emptySlot: { minHeight: 76, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, marginBottom: 16, borderRadius: 17, borderWidth: 1, borderStyle: 'dashed', borderColor: '#3C3C3C' }, plusCircle: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#777' }, emptySlotText: { color: '#E5E5E5', fontSize: 16, fontWeight: '700' }, createButton: { minHeight: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 13, borderRadius: 32, backgroundColor: LIME }, createButtonText: { color: '#080808', fontSize: 20, fontWeight: '900' },
  filters: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 26 }, select: { flex: 1, minWidth: 0, height: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 5, paddingHorizontal: 13, borderRadius: 13, borderWidth: 1, borderColor: '#444', backgroundColor: '#060606' }, selectActive: { borderColor: LIME }, selectText: { flex: 1, color: '#F2F2F2', fontSize: 14, fontWeight: '600' }, selectTextActive: { color: LIME }, filterButton: { width: 48, height: 48, borderRadius: 13, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#444' }, backdrop: { flex: 1, justifyContent: 'center', paddingHorizontal: 28, backgroundColor: 'rgba(0,0,0,0.72)' }, optionMenu: { width: '100%', maxWidth: 440, alignSelf: 'center', overflow: 'hidden', borderRadius: 17, borderWidth: 1, borderColor: '#3B3B3B', backgroundColor: '#141514' }, option: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#333' }, optionActive: { backgroundColor: '#1A210F' }, optionText: { color: '#FFF', fontSize: 16 }, optionTextActive: { color: LIME, fontWeight: '700' }, section: { marginBottom: 26 }, sectionTitle: { color: '#FFF', fontSize: 22, fontWeight: '800' }, dateRange: { marginTop: 4, color: '#B1B1B1', fontSize: 15 }, summary: { flexDirection: 'row', gap: 10, marginTop: 16 }, summaryCompact: { flexWrap: 'wrap' }, sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 13 }, analyticsLink: { color: LIME, fontSize: 15, fontWeight: '600' }, list: { gap: 12 }, insight: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 18, paddingHorizontal: 16, borderRadius: 13, borderWidth: 1, borderColor: '#486500' }, insightText: { flex: 1, color: '#F5F5F5', fontSize: 15, lineHeight: 21 }, autoLearnIntro: { marginBottom: 16 }, autoLearnTitle: { color: '#FFF', fontSize: 19, fontWeight: '800' }, autoLearnCopy: { maxWidth: 600, marginTop: 5, color: '#AFAFAF', fontSize: 14, lineHeight: 20 }, actions: { width: '100%', gap: 12 }, stateCard: { minHeight: 170, alignItems: 'center', justifyContent: 'center', padding: 24, borderRadius: 17, borderWidth: 1, borderColor: '#303030', backgroundColor: '#0A0A0A' }, stateTitle: { color: '#FFF', fontSize: 18, fontWeight: '700' }, stateCopy: { marginTop: 8, color: '#AAA', fontSize: 14, lineHeight: 20, textAlign: 'center' }, retry: { minHeight: 44, justifyContent: 'center', marginTop: 16, paddingHorizontal: 18, borderRadius: 22, borderWidth: 1, borderColor: LIME }, retryText: { color: LIME, fontWeight: '700' }, hiddenStateTrigger: { height: 1, opacity: 0 },
});
